// Edit this file to update the invitation content without changing the page layout.
import elenlyovImage from '../assets/pics/elenlyov.jpg';
import homeImage from '../assets/pics/bribehouse.png';
import groomHouseImage from '../assets/pics/groomhouse.png';
import churchImage from '../assets/pics/church.png';
import zagsImage from '../assets/pics/zags.png';
import restorantImage from '../assets/pics/restorant.png';

const appearance = {
  timeline: {
    eventGap: '3rem',
    timeSize: 'clamp(6.5rem, 26vw, 10rem)',
    captionSize: '2.6rem',
    maxWidth: '25rem',
  },
};

const eventAssets = [
  {
    id: 'groom-house',
    number: '01',
    time: '11:00',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Aghababyan+Hotel',
    image: groomHouseImage,
    enabled: true,
  },
  {
    id: 'bride-house',
    number: '02',
    time: '12:00',
    mapUrl: 'https://maps.app.goo.gl/gG79oo6hbpifjj3x9',
    image: homeImage,
    enabled: true,
  },
  {
    id: 'church',
    number: '03',
    time: '15:00',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Hovhannavank+Monastery+Aragatsotn+Armenia',
    image: churchImage,
    enabled: true,
  },
  {
    id: 'zags',
    number: '04',
    time: '16:00',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Hovhannavank+Monastery+Aragatsotn+Armenia',
    image: zagsImage,
    enabled: true,
  },
  {
    id: 'reception',
    number: '05',
    time: '17:00',
    mapUrl: 'https://www.google.com/maps/search/?api=1&query=Adana+restaurant+complex+Armenia',
    image: restorantImage,
    enabled: true,
  },
];

const localizedContent = {
  hy: {
    couple: { partnerOne: 'Էլեն', partnerTwo: 'Լյովա', combinedName: 'ԷԼԵՆ & ԼՅՈՎԱ', initials: { partnerOne: 'Է', partnerTwo: 'Լ' } },
    wedding: {
      date: '2026-10-25T14:00:00+04:00',
      displayDate: '20 · 10 · 2026',
      longDate: 'Երեքշաբթի · 20 Հոկտեմբեր · 2026',
      locale: 'hy-AM',
      timezone: 'Asia/Yerevan',
      rsvpDeadline: '2026-10-15T23:59:59+04:00',
    },
    cover: {
      note: 'A day to remember',
      buttonText: 'Բացել',
      image: elenlyovImage,
      imageAlt: 'Հարսանյաց վայրի նկարազարդում',
    },
    hero: {
      eyebrow: 'ՄԵՐ ՀԱՐՍԱՆԻՔԸ',
      title: 'ԷԼԵՆ & ԼՅՈՎԱ',
      invitationText: 'Սիրով հրավիրում ենք Ձեզ ներկա գտնվելու մեր հարսանյաց արարողությանը։',
      image: elenlyovImage,
      imageAlt: 'Հարսանյաց վայրի նկարազարդում',
    },
    introduction: {
      kicker: 'Հարգելի՛ հյուրեր',
      heading: 'Մեր պատմությունը շարունակվում է',
      emphasis: 'Ձեզ հետ միասին',
      paragraphs: ['Սիրով հրավիրում ենք Ձեզ կիսելու մեզ հետ մեր կյանքի կարևորագույն օրը։'],
    },
    itinerary: {
      kicker: 'Տոնակատարությունը',
      heading: 'Երեք վայր,',
      emphasis: 'մեկ գեղեցիկ օր',
      description: 'Պահպանեք ստորև նշված ժամերը և քարտեզի հղումներով գտեք յուրաքանչյուր վայրի ճանապարհը։',
    },
    calendar: {
      kicker: 'Our Day',
      heading: 'Սիրելի՛ Հյուրեր,',
      leadText: 'Սիրով հրավիրում ենք Ձեզ ներկա գտնվելու մեր հարսանյաց արարողությանը։',
      description: 'Սիրով հրավիրում ենք Ձեզ ներկա գտնվելու մեր հարսանյաց արարողությանը։ Ծանոթացեք օրվա ծրագրին և հաստատեք Ձեր ներկայությունը։',
      weekdays: ['Երկ', 'Երք', 'Չոր', 'Հնգ', 'Ուրբ', 'Շաբ', 'Կիր'],
      rail: {
        ariaLabel: 'Հոկտեմբեր 2026, հարսանիքի օրը՝ հոկտեմբերի 20-ին',
        heading: 'Հոկտեմբեր 2026',
        days: [['18', 'Կիր'], ['19', 'Երկ'], ['20', 'Երք'], ['21', 'Չոր'], ['22', 'Հնգ']],
      },
    },
    gallery: {
      image: elenlyovImage,
      imageAlt: 'Էլենի և Լյովայի լուսանկարը',
      closingPhotoAlts: ['Էլենի և Լյովայի լուսանկար 1', 'Էլենի և Լյովայի լուսանկար 2', 'Էլենի և Լյովայի լուսանկար 3'],
      memoryMainAlt: 'Ձեռքեր, որոնք ձգվում են միմյանց դեպի',
      memoryDetailAlt: 'Ձեռքեր, որոնք ձգվում են միմյանց դեպի եկեղեցու մոտ',
    },
    location: {
      kicker: 'Վայրը',
      heading: 'Location',
      emphasis: 'for you',
      description: 'Մեզ համար կարևոր յուրաքանչյուր պահը կանցկացնենք գեղեցիկ և սիրելի վայրերում։',
      mapButtonText: 'Քարտեզ',
    },
    timing: { kicker: 'Օրվա ծրագիր', heading: 'Օրվա ծրագիրը', emphasis: 'special' },
    events: {
      'groom-house': {
        title: 'Աղաբաբյանս հյուրանոց',
        timelineTitle: 'Փեսայի տուն',
        addressTitle: 'Աղաբաբյանս հյուրանոց',
        venue: 'Աղաբաբյանս հյուրանոց',
        address: '',
        imageAlt: 'Փեսայի տան նկարազարդում',
      },
      'bride-house': {
        title: 'Հարսի տուն',
        timelineTitle: 'Հարսի տուն',
        addressTitle: '',
        venue: '',
        address: '',
        imageAlt: 'Հարսի տան նկարազարդում',
      },
      church: {
        title: 'Հովհանավանք',
        timelineTitle: 'Պսակադրություն',
        addressTitle: 'Հովհաննավանք',
        venue: 'Հովհանավանք',
        address: '',
        imageAlt: 'Սուրբ Հռիփսիմե եկեղեցու նկարազարդում',
      },
      zags: {
        title: 'Ամուսնության գրանցում',
        timelineTitle: 'Ամուսնության գրանցում',
        addressTitle: 'Ադանա ռեստորանային համալիրի բակ',
        venue: 'Ադանա ռեստորանային համալիր',
        address: '',
        imageAlt: 'Ադանա Ռեստորանային համալիրի նկարազարդում',
      },
      reception: {
        title: 'Հարսանյաց հանդիսություն',
        timelineTitle: 'Հարսանյաց հանդիսություն',
        addressTitle: 'Ադանա ռեստորանային համալիր',
        venue: 'Ադանա ռեստորանային համալիր',
        address: '',
        imageAlt: 'Ռեստորանի նկարազարդում',
      },
    },
    countdown: { heading: 'Մնացել է․․․', labels: { days: 'ՕՐ', hours: 'ԺԱՄ', minutes: 'ՐՈՊԵ', seconds: 'ՎՐԿ' } },
    notes: {
      kicker: 'Օրվա մասին',
      items: [
        { icon: 'calendar', title: 'Ինչ է սպասվում', text: 'Ջերմ ընդունելություն, եկեղեցական օրհնություն, ընտանեկան լուսանկարներ, ընթրիք, երաժշտություն և պարեր։' },
        { icon: 'heart', title: 'Սիրով', text: 'Ձեր ներկայությունը մեզ համար ամենամեծ նվերն է։ Եկեք և միասին նշենք մեր նոր սկիզբը։' },
      ],
    },
    rsvp: {
      enabled: true,
      kicker: 'RSVP',
      heading: 'Խնդրում ենք հաստատել Ձեր ներկայությունը',
      description: '',
      namePlaceholder: 'Ձեր անունը',
      guestCountPlaceholder: 'Հյուրերի քանակը',
      attendancePlaceholder: 'Կկարողանա՞ք ներկա գտնվել',
      invitedByPlaceholder: 'Ում կողմից եք հրավիրված',
      invitedByOptions: [{ value: 'bride', label: 'Հարսի կողմից' }, { value: 'groom', label: 'Փեսայի կողմից' }],
      attendanceOptions: [{ value: 'yes', label: 'Այո, սիրով կմասնակցեմ' }, { value: 'no', label: 'Ցավոք, չեմ կարողանա մասնակցել' }],
      submitButtonText: 'Ուղարկել պատասխանը',
      sendingText: 'Ուղարկվում է…',
      successMessage: 'Ձեր պատասխանը ուղարկված է։ Շնորհակալություն։',
      invalidGuestCountMessage: 'Մասնակցելու դեպքում խնդրում ենք նշել առնվազն մեկ հյուր։',
      missingWebhookUrlMessage: 'RSVP webhook հասցեն կարգավորված չէ։',
      errorMessage: 'Չհաջողվեց ուղարկել պատասխանը։ Խնդրում ենք կրկին փորձել։',
    },
    meta: {
      documentTitleSuffix: 'Հարսանեկան հրավեր',
      languageSelectorAriaLabel: 'Լեզվի ընտրիչ',
      coverAriaLabel: 'Հրավերի կազմ',
      closingAriaLabel: 'Եզրափակիչ ուղերձ',
    },
    footer: {
      closingMessage: 'Սիրով սպասում ենք Ձեզ',
    },
  },
  ru: {
    couple: { partnerOne: 'Элен', partnerTwo: 'Лёв', combinedName: 'ЭЛЕН & ЛЁВ', initials: { partnerOne: 'Э', partnerTwo: 'Л' } },
    wedding: {
      date: '2026-10-25T14:00:00+04:00',
      displayDate: '20 · 10 · 2026',
      longDate: 'Вторник · 20 Октября · 2026',
      locale: 'ru-RU',
      timezone: 'Asia/Yerevan',
      rsvpDeadline: '2026-10-15T23:59:59+04:00',
    },
    cover: {
      note: 'A day to remember',
      buttonText: 'Открыть',
      image: elenlyovImage,
      imageAlt: 'Иллюстрация свадебного места',
    },
    hero: {
      eyebrow: 'НАША СВАДЬБА',
      title: 'ЭЛЕН & ЛЁВ',
      invitationText: 'С любовью приглашаем вас разделить с нами наш свадебный день.',
      image: elenlyovImage,
      imageAlt: 'Иллюстрация свадебного места',
    },
    introduction: {
      kicker: 'Дорогие гости',
      heading: 'Наша история продолжается',
      emphasis: 'вместе с вами',
      paragraphs: ['С любовью приглашаем вас разделить с нами самый важный день нашей жизни.'],
    },
    itinerary: {
      kicker: 'Празднование',
      heading: 'Три места,',
      emphasis: 'один прекрасный день',
      description: 'Сохраните указанное ниже расписание и откройте маршрут к каждому месту по ссылкам на карте.',
    },
    calendar: {
      kicker: 'Our Day',
      heading: 'Дорогие гости,',
      leadText: 'С любовью приглашаем вас на нашу свадебную церемонию.',
      description: 'С любовью приглашаем вас на нашу свадебную церемонию. Ознакомьтесь с программой дня и подтвердите ваше присутствие.',
      weekdays: ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс'],
      rail: {
        ariaLabel: 'Октябрь 2026, день свадьбы 20 октября',
        heading: 'Октябрь 2026',
        days: [['18', 'Вс'], ['19', 'Пн'], ['20', 'Вт'], ['21', 'Ср'], ['22', 'Чт']],
      },
    },
    gallery: {
      image: elenlyovImage,
      imageAlt: 'Фотография Элен и Лёва',
      closingPhotoAlts: ['Фотография Элен и Лёва 1', 'Фотография Элен и Лёва 2', 'Фотография Элен и Лёва 3'],
      memoryMainAlt: 'Руки, тянущиеся друг к другу',
      memoryDetailAlt: 'Руки, тянущиеся друг к другу у церкви',
    },
    location: {
      kicker: 'Место',
      heading: 'Location',
      emphasis: 'for you',
      description: 'Каждое важное мгновение этого дня мы проведем в красивых и любимых местах.',
      mapButtonText: 'Карта',
    },
    timing: { kicker: 'Программа дня', heading: 'Программа дня', emphasis: 'special' },
    events: {
      'groom-house': {
        title: 'Отель Агабабянс',
        timelineTitle: 'Дом жениха',
        addressTitle: 'Отель Агабабянс',
        venue: 'Отель Агабабянс',
        address: '',
        imageAlt: 'Иллюстрация дома жениха',
      },
      'bride-house': {
        title: 'Дом невесты',
        timelineTitle: 'Дом невесты',
        addressTitle: '',
        venue: '',
        address: '',
        imageAlt: 'Иллюстрация дома невесты',
      },
      church: {
        title: 'Ованнаванк',
        timelineTitle: 'Венчание',
        addressTitle: 'Ованнаванк',
        venue: 'Ованнаванк',
        address: '',
        imageAlt: 'Иллюстрация церкви',
      },
      zags: {
        title: 'Регистрация брака',
        timelineTitle: 'Регистрация брака',
        addressTitle: 'Двор ресторанного комплекса Адана',
        venue: 'Ресторанный комплекс Адана',
        address: '',
        imageAlt: 'Иллюстрация комплекса Адана',
      },
      reception: {
        title: 'Свадебное торжество',
        timelineTitle: 'Свадебное торжество',
        addressTitle: 'Ресторанный комплекс Адана',
        venue: 'Ресторанный комплекс Адана',
        address: '',
        imageAlt: 'Иллюстрация ресторана',
      },
    },
    countdown: { heading: 'Осталось…', labels: { days: 'ДН', hours: 'ЧАС', minutes: 'МИН', seconds: 'СЕК' } },
    notes: {
      kicker: 'О дне',
      items: [
        { icon: 'calendar', title: 'Что вас ждет', text: 'Теплая встреча, церковное благословение, семейные фотографии, ужин, музыка и танцы.' },
        { icon: 'heart', title: 'С любовью', text: 'Ваше присутствие - самый большой подарок для нас. Приходите, чтобы вместе отпраздновать наше новое начало.' },
      ],
    },
    rsvp: {
      enabled: true,
      kicker: 'RSVP',
      heading: 'Пожалуйста, подтвердите ваше присутствие',
      description: '',
      namePlaceholder: 'Ваше имя',
      guestCountPlaceholder: 'Количество гостей',
      attendancePlaceholder: 'Вы придете?',
      invitedByPlaceholder: 'Кто вас пригласил',
      invitedByOptions: [{ value: 'bride', label: 'Со стороны невесты' }, { value: 'groom', label: 'Со стороны жениха' }],
      attendanceOptions: [{ value: 'yes', label: 'Да, с радостью приду' }, { value: 'no', label: 'К сожалению, не смогу прийти' }],
      submitButtonText: 'Отправить ответ',
      sendingText: 'Отправка…',
      successMessage: 'Ваш ответ отправлен. Спасибо.',
      invalidGuestCountMessage: 'Если вы участвуете, укажите хотя бы одного гостя.',
      missingWebhookUrlMessage: 'Адрес webhook для RSVP не настроен.',
      errorMessage: 'Не удалось отправить ответ. Пожалуйста, попробуйте снова.',
    },
    meta: {
      documentTitleSuffix: 'Свадебное приглашение',
      languageSelectorAriaLabel: 'Переключатель языка',
      coverAriaLabel: 'Обложка приглашения',
      closingAriaLabel: 'Заключительное сообщение',
    },
    footer: {
      closingMessage: 'С любовью ждем вас',
    },
  },
  en: {
    couple: { partnerOne: 'Elen', partnerTwo: 'Lyov', combinedName: 'ELEN & LYOV', initials: { partnerOne: 'E', partnerTwo: 'L' } },
    wedding: {
      date: '2026-10-25T14:00:00+04:00',
      displayDate: '20 · 10 · 2026',
      longDate: 'Tuesday · 20 October · 2026',
      locale: 'en-US',
      timezone: 'Asia/Yerevan',
      rsvpDeadline: '2026-10-15T23:59:59+04:00',
    },
    cover: {
      note: 'A day to remember',
      buttonText: 'Open',
      image: elenlyovImage,
      imageAlt: 'Wedding location illustration',
    },
    hero: {
      eyebrow: 'OUR WEDDING',
      title: 'ELEN & LYOV',
      invitationText: 'With love, we invite you to share our wedding day with us.',
      image: elenlyovImage,
      imageAlt: 'Wedding location illustration',
    },
    introduction: {
      kicker: 'Dear guests',
      heading: 'Our story continues',
      emphasis: 'with you by our side',
      paragraphs: ['With love, we invite you to share one of the most important days of our lives.'],
    },
    itinerary: {
      kicker: 'Celebration',
      heading: 'Three places,',
      emphasis: 'one beautiful day',
      description: 'Save the schedule below and use map links to find your way to each venue.',
    },
    calendar: {
      kicker: 'Our Day',
      heading: 'Dear Guests,',
      leadText: 'With love, we invite you to attend our wedding ceremony.',
      description: 'With love, we invite you to attend our wedding ceremony. Review the day plan and confirm your attendance.',
      weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      rail: {
        ariaLabel: 'October 2026, wedding day is on October 20',
        heading: 'October 2026',
        days: [['18', 'Sun'], ['19', 'Mon'], ['20', 'Tue'], ['21', 'Wed'], ['22', 'Thu']],
      },
    },
    gallery: {
      image: elenlyovImage,
      imageAlt: 'Photo of Elen and Lyov',
      closingPhotoAlts: ['Photo of Elen and Lyov 1', 'Photo of Elen and Lyov 2', 'Photo of Elen and Lyov 3'],
      memoryMainAlt: 'Hands reaching for each other',
      memoryDetailAlt: 'Hands reaching for each other at the church',
    },
    location: {
      kicker: 'Location',
      heading: 'Location',
      emphasis: 'for you',
      description: 'We will spend every meaningful moment in beautiful places close to our hearts.',
      mapButtonText: 'Map',
    },
    timing: { kicker: 'Day Schedule', heading: 'Day Schedule', emphasis: 'special' },
    events: {
      'groom-house': {
        title: 'Aghababyan\'s Hotel',
        timelineTitle: 'Groom\'s House',
        addressTitle: 'Aghababyan\'s Hotel',
        venue: 'Aghababyan\'s Hotel',
        address: '',
        imageAlt: 'Groom\'s house illustration',
      },
      'bride-house': {
        title: 'Bride\'s House',
        timelineTitle: 'Bride\'s House',
        addressTitle: '',
        venue: '',
        address: '',
        imageAlt: 'Bride\'s house illustration',
      },
      church: {
        title: 'Hovhannavank',
        timelineTitle: 'Wedding Ceremony',
        addressTitle: 'Hovhannavank',
        venue: 'Hovhannavank',
        address: '',
        imageAlt: 'Church illustration',
      },
      zags: {
        title: 'Marriage Registration',
        timelineTitle: 'Marriage Registration',
        addressTitle: 'Courtyard of Adana Restaurant Complex',
        venue: 'Adana Restaurant Complex',
        address: '',
        imageAlt: 'Adana complex illustration',
      },
      reception: {
        title: 'Wedding Reception',
        timelineTitle: 'Wedding Reception',
        addressTitle: 'Adana Restaurant Complex',
        venue: 'Adana Restaurant Complex',
        address: '',
        imageAlt: 'Restaurant illustration',
      },
    },
    countdown: { heading: 'Time left…', labels: { days: 'DAY', hours: 'HOUR', minutes: 'MIN', seconds: 'SEC' } },
    notes: {
      kicker: 'About the day',
      items: [
        { icon: 'calendar', title: 'What to expect', text: 'A warm welcome, church blessing, family photos, dinner, music, and dancing.' },
        { icon: 'heart', title: 'With love', text: 'Your presence is the greatest gift to us. Join us as we celebrate our new beginning.' },
      ],
    },
    rsvp: {
      enabled: true,
      kicker: 'RSVP',
      heading: 'Please confirm your attendance',
      description: '',
      namePlaceholder: 'Your name',
      guestCountPlaceholder: 'Number of guests',
      attendancePlaceholder: 'Will you attend?',
      invitedByPlaceholder: 'Who invited you',
      invitedByOptions: [{ value: 'bride', label: 'Bride side' }, { value: 'groom', label: 'Groom side' }],
      attendanceOptions: [{ value: 'yes', label: 'Yes, I will attend with pleasure' }, { value: 'no', label: 'Unfortunately, I cannot attend' }],
      submitButtonText: 'Send response',
      sendingText: 'Sending…',
      successMessage: 'Your response has been sent. Thank you.',
      invalidGuestCountMessage: 'If attending, please specify at least one guest.',
      missingWebhookUrlMessage: 'RSVP webhook URL is not configured.',
      errorMessage: 'Failed to send your response. Please try again.',
    },
    meta: {
      documentTitleSuffix: 'Wedding Invitation',
      languageSelectorAriaLabel: 'Language selector',
      coverAriaLabel: 'Invitation cover',
      closingAriaLabel: 'Closing message',
    },
    footer: {
      closingMessage: 'We look forward to celebrating with you',
    },
  },
};

export function getWeddingConfig(language = 'hy') {
  const normalizedLanguage = localizedContent[language] ? language : 'hy';
  const content = localizedContent[normalizedLanguage];

  return {
    appearance,
    ...content,
    events: eventAssets.map((event) => ({
      ...event,
      ...content.events[event.id],
    })),
  };
}

export const weddingConfig = getWeddingConfig('hy');
